docsfix/Upload docs

diff --git a/.github/workflows/cicd-admin.yaml b/.github/workflows/cicd-admin.yaml
--- a/.github/workflows/cicd-admin.yaml
+++ b/.github/workflows/cicd-admin.yaml
@@ -11,6 +11,7 @@ env:                                                          # Commit & push up
 
   GH_ADMIN_USER_NAME_PARAMETER: AP_GH_ADMIN_USER_NAME 
   GH_ADMIN_USER_EMAIL_PARAMETER: AP_GH_ADMIN_USER_EMAIL
+  GH_ADMIN_TOKEN_PARAMETER: AP_GH_ADMIN_TOKEN
   SLACK_GHA_NOTIFY_BOT_TOKEN_PARAMETER: AP_SLACK_GHA_NOTIFY_BOT_TOKEN
   SLACK_CHANNEL_ID: ${{ secrets.REPO_SLACK_CHANNEL_ID }}
 
@@ -110,9 +111,49 @@ jobs:
             --with-decryption \
             --output text)" >> $GITHUB_ENV
 
+      - name: Check for GH_ADMIN_TOKEN in AWS SSM Parameter Store
+        id: check-gh-admin-token
+        if: ${{ steps.get-gh-admin-user-email.outcome == 'success' }}
+        run: |
+          aws ssm get-parameter \
+            --region "${{ env.AWS_REGION }}" \
+            --name "${{ env.GH_ADMIN_TOKEN_PARAMETER }}" \
+            --query "Parameter.Value" \
+            --no-with-decryption \
+            --output text
+
+          GH_ADMIN_TOKEN_FOUND=$?
+
+          if [[ $GH_ADMIN_TOKEN_FOUND == '0' ]];
+          then
+            echo "GH_ADMIN_TOKEN_FOUND=0" >> $GITHUB_ENV
+          else
+            echo "GH_ADMIN_TOKEN_FOUND=1" >> $GITHUB_ENV
+
+            echo "GH_ADMIN_TOKEN not found."
+          fi
+
+      - name: Get GH_ADMIN_TOKEN from AWS SSM Parameter Store
+        id: get-gh-admin-token
+        if: ${{ steps.check-gh-admin-token.outcome == 'success' && env.GH_ADMIN_TOKEN_FOUND == '0' }}
+        run: |
+          echo "::add-mask::$(aws ssm get-parameter \
+            --region "${{ env.AWS_REGION }}" \
+            --name "${{ env.GH_ADMIN_TOKEN_PARAMETER }}" \
+            --query "Parameter.Value" \
+            --with-decryption \
+            --output text)"
+          
+          echo "GH_ADMIN_TOKEN=$(aws ssm get-parameter \
+            --region "${{ env.AWS_REGION }}" \
+            --name "${{ env.GH_ADMIN_TOKEN_PARAMETER }}" \
+            --query "Parameter.Value" \
+            --with-decryption \
+            --output text)" >> $GITHUB_ENV
+
       - name: Check for SLACK_GHA_NOTIFY_BOT_TOKEN in AWS SSM Parameter Store
         id: check-slack-gha-notify-bot-token
-        if: ${{ steps.get-gh-admin-user-email.outcome == 'success' }}
+        if: ${{ steps.get-gh-admin-token.outcome == 'success' }}
         run: |
           aws ssm get-parameter \
             --region "${{ env.AWS_REGION }}" \
@@ -175,11 +216,15 @@ jobs:
           echo "COMMIT_MESSAGE_2=${{ env.COMMIT_MESSAGE_1 }}" >> $GITHUB_ENV
           echo "COMMIT_MESSAGE_3=$(echo \"${{ env.COMMIT_MESSAGE_1 }}\")" >> $GITHUB_ENV
 
+      - name: Authenticate GitHub CLI
+        id: authenticate-github-cli
+        if: ${{ steps.get-commit-message-2-and-3.outcome == 'success' }}
+        run: |
+          echo ${{ env.GH_ADMIN_TOKEN }} | gh auth login --with-token
+
       - name: Open PR
         id: open-pr
-        if: ${{ steps.get-commit-message-2-and-3.outcome == 'success' }}
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        if: ${{ steps.authenticate-github-cli.outcome == 'success' }}
         run: |
           gh pr create \
             --head "${{ env.BRANCH }}" \
@@ -190,8 +235,6 @@ jobs:
       - name: Merge PR
         id: merge-pr
         if: ${{ steps.open-pr.outcome == 'success' }}
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           gh pr merge --merge
 
